### ISSUE TITLE
Not an issue, just a thank you...

### ISSUE THREAD

**Issue by robault** [qmfrederik/AS.TurboJpegWrapper#1]
Hey there, 

Since GitHub doesn't have private messaging (anymore) I wasn't sure how to contact you to thank you for making this C# wrapper for libjpeg-turbo. I am building an over-network game capture application and was using the .Net Image.Save method to compress to Jpeg but it was slowing down my frame rate. Using your NuGet package I was able to increase the frame rate 5-10 FPS with two lines of code. That actually brought my apps FPS right up to 60 which is exactly where I wanted it to be. Anyway, I really appreciate it, thank you!

--Robert

**Comment by qmfrederik** [comment]
Hi @robault ,

You're welcome, thanks for the feedback, really appreciate it!

Frederik.
