### ISSUE TITLE
"Unable to load DLL 'turbojpeg' - OS X

### ISSUE THREAD

**Issue by aseemgautam** [qmfrederik/AS.TurboJpegWrapper#5]
I am getting this error on line - 
`TJCompressor compressor = new TJCompressor();`

I have copied turbojpeg.dll file from the source project to bin/nuget folder. Does not work. Is there any additional step required to use this wrapper on OS X?

**Comment by qmfrederik** [comment]
Did you add a reference to `/runtime.osx.10.10-x64.Quamotion.TurboJpegWrapper`? `.dll` files don't work on macOS; you need `.dylib` files and that package contains the dylib files.

**Comment by qmfrederik** [comment]
Sorry, didn't get the fact that you're using Mono. I've never tested this on Mono, but if this configuration works for you, no need to change it :)

**Comment by aseemgautam** [comment]
.NET core on OS X High Sierra. Using VS for mac.

**Comment by qmfrederik** [comment]
Fixed via #6 .
